apiVersion: v1
kind: ServiceAccount
metadata:
   name: dev-serviceaccount
   namespace: default  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-for-dev-serviceaccount
  namespace: default
rules:
- apiGroups: ["*","apps","extensions"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-for-dev-serviceaccount
  namespace: default
subjects:
- kind: ServiceAccount
  name: dev-serviceaccount
  namespace: default
roleRef:
  kind: Role
  name: role-for-dev-serviceaccount
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: dev-serviceaccount-secret
  namespace: default
  annotations:
      kubernetes.io/service-account.name: "dev-serviceaccount"
---